name 'evenup-time'
version '1.0.2'
author 'Justin Lambert <jlambert@letsevenup.com>'
license 'Apache'
summary 'Manages the timezone and ntp.'
description 'Installs, configures, and runs the ntp service.  Sets the local timezone.'
source 'http://git.ineu.us/'
project_page 'https://github.com/evenup/evenup-time'
dependency 'evenup/common', '>= 0.1.0'

